markdown: rdiscount
highlighter: true
plugins: ./blog/_plugins
paginate: 8

safe: false
baseurl: /blog
#站点基础配置
title: blog
subTitle: belongwqz blog.
description: 简简单单
url: http://belongwqz.github.io
feed: /blog/atom.xml

#菜单配置
nav:
  - text: 首页
    url: /blog/index.html
  - text: 文章归档
    url: /blog/archives.html
  - text: 作品
    url: /blog/works.html
  - text: 联系我
    url: http://belongwqz.github.io/blog/contact.html
  #- text: 博客源代码
  #  url: https://github.com/belongwqz/blog

#theme config
themes: /blog/themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /blog/themes/violet/images/hdbg01.jpg
  - item: /blog/themes/violet/images/hdbg02.jpg
  - item: /blog/themes/violet/images/hdbg03.jpg
  - item: /blog/themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-google-plus
    url: http://www.zhanxin.info
  - class: fa-facebook
    url: http://www.zhanxin.info
  - class: fa-github
    url: http://github.com/pizn
  - class: fa-weibo
    url: http://weibo.com/pizner
  - class: fa-renren
    url: http://www.zhanxin.info
  - class: fa-pinterest
    url: http://www.zhanxin.info
  - class: fa-twitter
    url: http://www.zhanxin.info
  - class: fa-rss
    url: http://www.zhanxin.info

#作者信息
author:
  link: http://www.zhanxin.info/contact.html
  img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1


#评论信息
disqus:
  config: true
  id: piznblog

duoshuo:
  config: false
  id: zhanxin
