markdown: rdiscount
highlighter: true
plugins: ./blog/_plugins
paginate: 8

safe: false
baseurl: /
#站点基础配置
title: Beautiful
subTitle: Something never changes, but something does.
description: 简简单单
url: http://keepwalk.cn
feed: /blog/atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
  - text: 归档
    url: /archives.html
  - text: 记忆
    url: /memory.html
  - text: 联系我
    url: /contact.html

#theme config
themes: /themes/violet

#memory
mem:
  - img: images/mem/hy.jpg
    w: 587
    h: 628
  - img: images/mem/hy1.jpg
    w: 335
    h: 539
  - img: images/mem/hy2.jpg
    w: 451
    h: 603
  - img: images/mem/hy3.jpg
    w: 670
    h: 503
  - img: images/mem/hy4.jpg
    w: 516
    h: 628
  - img: images/mem/hy5.jpg
    w: 640
    h: 853
    
#配置你喜欢的顶部背景图片
headimg:
  - item: /themes/violet/images/hdbg01.jpg
  - item: /themes/violet/images/hdbg02.jpg
  - item: /themes/violet/images/hdbg03.jpg
  - item: /themes/violet/images/hdbg04.jpg

#关注我
#follow:
#  - class: fa-google-plus
#    url: http://www.zhanxin.info
#  - class: fa-facebook
#    url: http://www.zhanxin.info
#  - class: fa-github
#    url: http://github.com/pizn
#  - class: fa-weibo
#    url: http://weibo.com/pizner
#  - class: fa-renren
#    url: http://www.zhanxin.info
#  - class: fa-pinterest
#    url: http://www.zhanxin.info
#  - class: fa-twitter
#    url: http://www.zhanxin.info
#  - class: fa-rss
#    url: http://www.zhanxin.info

#作者信息
author:
  link: http://belongwqz.github.io/blog/contact.html
  img: http://tp2.sinaimg.cn/1832671293/180/40020872447/1


#评论信息
disqus:
  config: true
  id: belongwqz

duoshuo:
  config: true
  id: belongwqz
